### ISSUE TITLE
Better CSS 

### ISSUE THREAD

**Issue by Fiftyllama** [sam-grierson/Group-Project#2]
We need to have local css? if someone could elaborate on what this entails?

**Comment by 0xMo** [comment]
I am working in that

**Comment by sam-grierson** [comment]
I think because the the site is going to be on the VM and we cant guarantee its going to have a external connection in the lab we will need to use local CSS. If we want to use the stuff that @0xMo has on his coursework i think that looks pretty good.

**Comment by 0xMo** [comment]
I have updated some of the issues related to CSS, please have a look at it!
The login works, but it does not show anything yet. Because I am wondering where to show the name.
I havent test the registration yet, because it has too many field compare to the database, which needed to be updated before I test it.

**Comment by 0xMo** [comment]
I guess this issued could be closed as well
